orthodontist/appointment/urls.py
from django.urls import path
from . import views


app_name = 'appointment'
urlpatterns = [
    path('', views.AppointmentView.as_view(), name='index'),
    path('get_clinics/', views.get_clinics, name='get_clinics'),
    path('get_dates/', views.get_dates, name='get_dates'),
    path('get_timetable/', views.get_timetable, name='get_timetable'),
    path('<int:pk>/delete_appointment/', views.delete_appointment, name='delete_appointment'),
    path('get_clinics_for_map/', views.ClinicsForMap.as_view(), name='get_clinics_for_map'),
]

orthodontist/ask/urls.py
from django.urls import path
from . import views



app_name = 'ask'
urlpatterns = [
    path('', views.AskView.as_view(), name='index'),
    path('<int:pk>/', views.QuestionDetail.as_view(), name='question'),
    path('ask/', views.AskQuestionView.as_view(), name='ask_question'),
    path('<int:pk>/delete_question/', views.delete_question, name='delete_question'),
    path('<int:pk>/delete_answer/', views.delete_answer, name='delete_answer'),
    path('<int:pk>/like/', views.like_question, name='like'),
    path('ajax_sorting/', views.QuestionListAjax.as_view(), name='question_ajax'),
    path('<int:pk>/edit_question/', views.QuestionEdit.as_view(), name='edit_question'),
]

orthodontist/orthodontist/urls.py
from django.contrib import admin
from django.urls import path, include
from index import views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('about/', views.about, name='about'),
    path('admin/', admin.site.urls),
    path('question/', include('ask.urls')),
    path('appointment/', include('appointment.urls')),
    path('feedback/', include('feedback.urls')),
    path('signup/', views.signup, name='signup'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('user/<int:pk>/', views.UserView.as_view(), name='user'),
    path('user/<int:pk>/popular/', views.UserViewPopular.as_view(), name='user_popular'),
    path('user/<int:pk>/update/', views.UserViewUpdate.as_view(), name='update'),
    path('user/<int:pk>/appointments/', views.UserViewAppointments.as_view(), name='appointments'),
    path('search/', views.SearchResults.as_view(), name='search'),

]

if bool(settings.DEBUG):
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orthodontist/appointment/models.py
from django.db import models
from django.utils import timezone


class Clinic(models.Model):
    name = models.CharField(max_length=100, verbose_name='Название клиника', unique=True)
    address = models.CharField(max_length=100, verbose_name='Адрес клиники', unique=True)
    latitude = models.DecimalField(verbose_name='Широта', max_digits=12, decimal_places=9)
    longitude = models.DecimalField(verbose_name='Долгота', max_digits=12, decimal_places=9)
    phone_number1 = models.CharField(max_length=20, verbose_name='Номер телефона', blank=True)
    phone_number2 = models.CharField(max_length=20, verbose_name='Номер телефона(2)', blank=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'клинику'
        verbose_name_plural = 'клиники'


class Patient(models.Model):
    name = models.CharField(max_length=40, verbose_name='Имя')
    email = models.EmailField(max_length=40, verbose_name='Электронная почта', unique=True)
    phone_number = models.CharField(max_length=20, verbose_name='Номер телефона')

    def __str__(self):
        return self.email

    class Meta:
        verbose_name = 'пациента'
        verbose_name_plural = 'пациенты'

class Appointment(models.Model):
    clinic = models.ForeignKey(Clinic, on_delete=models.CASCADE, verbose_name='Название клиника')
    date = models.DateField(verbose_name='Дата приема')
    time = models.TimeField(verbose_name='Время приема')
    patient = models.ForeignKey(Patient, on_delete=models.SET_NULL, null=True, default=None, blank=True,
                                verbose_name='Пациент')
    problem = models.TextField(max_length=1000, verbose_name='Описание проблемы', null=True, default=None, blank=True)

    def __str__(self):
        return f'Прием № {self.id}'

    def is_available(self):
        if self.date > timezone.now().date() and not self.patient:
            return '- свободно -'
        elif self.patient:
            return '- запись -'
        else:
            return '- просрочено -'
    is_available.short_description = 'Статус'

    class Meta:
        unique_together = ('date', 'time')
        verbose_name = 'запись на прием'
        verbose_name_plural = 'записи на прием'
        ordering = ['date', 'time', 'clinic']

orthodontist/appointment/forms.py
from django import forms
from .models import Patient, Appointment, Clinic
import re
from index.forms import ErrorClassMixin


class MyChoiceField(forms.ChoiceField):
    def valid_value(self, value):
        return True


class AppointmentForm(ErrorClassMixin, forms.Form):
    name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Имя'}),
                           label='Имя')
    email = forms.CharField(widget=forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'Email'}),
                            label='Email')
    phone_number = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Номер телефона'}),
                                   label='Номер телефона')
    clinic = MyChoiceField(widget=forms.Select(attrs={'class': 'form-select'}), label='Клиника')
    date = MyChoiceField(widget=forms.Select(attrs={'class': 'form-select'}), label='Дата')
    time = MyChoiceField(widget=forms.Select(attrs={'class': 'form-select'}), label='Время')
    description = forms.CharField(widget=forms.Textarea(attrs={'class': 'form-control', 'style': 'height: 100px', 'placeholder': 'Описание'}),
                                  label='Краткое изложение проблемы')

    def save(self):
        clinic = Clinic.objects.get(name=self.cleaned_data['clinic'])
        try:
            patient = Patient.objects.get(name=self.cleaned_data['name'],
                                          email=self.cleaned_data['email'],
                                          phone_number=self.cleaned_data['phone_number'])
        except Patient.DoesNotExist:
            patient, _ = Patient.objects.update_or_create(email=self.cleaned_data['email'],
                                                          defaults={'phone_number': self.cleaned_data['phone_number'],
                                                                    'name': self.cleaned_data['name']})
        appointment = Appointment.objects.filter(
            clinic=clinic, date=self.cleaned_data['date'], time=self.cleaned_data['time']
        ).update(patient=patient, problem=self.cleaned_data['description'])
        return appointment

    def clean_phone_number(self):
        phone_number = self.cleaned_data['phone_number']
        if not re.match(r'^\+[\d]{11}$', phone_number):
            raise forms.ValidationError('Телефон должен быть записан в формате +7XXXXXXXXXX.')
        return phone_number

    def clean_email(self):
        email = self.cleaned_data['email']
        if not re.match(r'^\S+@\S+\.\S+$', email):
            raise forms.ValidationError('Введите корректный электронный адрес.')
        return email

orthodontist/appointment/views.py
from django.shortcuts import reverse, get_object_or_404
from django.views.generic.edit import FormView
from django.utils import timezone
from django.contrib import messages
from django.http import JsonResponse, Http404, HttpResponseRedirect
from .forms import AppointmentForm
from .models import Clinic, Appointment
from .serializers import ClinicSerializer
from .tasks import send_email
from rest_framework.generics import ListAPIView


class AppointmentView(FormView):
    template_name = 'appointment/appointment.html'
    form_class = AppointmentForm

    def get_form_kwargs(self):
        kwargs = super(AppointmentView, self).get_form_kwargs()
        if self.request.method == 'POST' and self.request.user.is_authenticated:
            kwargs['data']._mutable = True
            kwargs['data']['name'] = self.request.user.first_name
            kwargs['data']['email'] = self.request.user.email
            kwargs['data']._mutable = False
        return kwargs

    def get_success_url(self):
        if self.request.user.is_authenticated:
            return reverse('appointments', args=[self.request.user.id])
        else:
            return reverse('appointment:index')

    def form_valid(self, form):
        form.save()
        send_email.delay(form.cleaned_data['date'], form.cleaned_data['time'],
                         form.cleaned_data['name'], form.cleaned_data['email'])
        messages.success(self.request, 'Вы успешно записались на прием. '
                                       'Сообщение с информацией о приеме отправлено на вашу почту')
        return super(AppointmentView, self).form_valid(form)

    def form_invalid(self, form):
        form.validation_error_class()
        return super(AppointmentView, self).form_invalid(form)
    
    
def get_clinics(request):
    if request.is_ajax():
        clinics = Clinic.objects.filter(appointment__patient=None,
                                        appointment__date__gt=timezone.now().date()).order_by('name')
        data = {'clinics': list(clinics.values_list('name', flat=True).distinct())}
        return JsonResponse(data, status=200)

def get_dates(request):
    if request.is_ajax():
        clinic = request.GET.get('clinic')
        appointments = Appointment.objects.filter(clinic__name=clinic,
                                                  date__gt=timezone.now().date(),
                                                  patient=None).order_by('date').distinct('date')
        data = {'dates': list(appointments.values_list('date', flat=True))}
        return JsonResponse(data, status=200)

def get_timetable(request):
    if request.is_ajax():
        clinic = request.GET.get('clinic')
        date = request.GET.get('date')
        appointments = Appointment.objects.filter(clinic__name=clinic,
                                                  date=date,
                                                  patient=None).order_by('time')
        data = {'timetable': list(appointments.values_list('time', flat=True))}
        return JsonResponse(data, status=200)

def delete_appointment(request, pk):
    appointment = get_object_or_404(Appointment, pk=pk)
    if request.user.email == appointment.patient.email:
        appointment.patient = None
        appointment.problem = None
        appointment.save()
        messages.success(request, 'Вы успешно отменили запись на прием.')
        return HttpResponseRedirect(reverse('appointments', args=[request.user.id]))
    else:
        raise Http404()


class ClinicsForMap(ListAPIView):
    queryset = Clinic.objects.all().order_by('name')
    serializer_class = ClinicSerializer
    pagination_class = None

    def initial(self, request, *args, **kwargs):
        if not request.is_ajax():
            raise Http404()
        return super(ClinicsForMap, self).initial(request, *args, **kwargs)

orthodontist/templates/appointment/appointment.html
{% extends "base.html" %}

{% block title %}Запись на прием | {{ block.super }}{% endblock %}

{% block content %}
<main class="container pb-5">
    <div class="row justify-content-center">
        <div class="col-lg-9 mb-3">
            <h2>Запись на прием</h2>
        </div>
    </div>
    <div class="row justify-content-center">
        <div class="col-lg-9 mb-3">
            {% if messages %}
            {% for message in messages %}
            <div class="alert alert-success" role="alert">{{ message }}</div>
            {% endfor %}
            {% endif %}
            {% block user_questions %}{% endblock %}
        </div>
    </div>
    <form method="post" class="needs-validation" novalidate>
        {% csrf_token %}
        <div class="row g-4 justify-content-center mb-3">
            <div class="col-lg-3">
                <div class="form-floating">
                    {% if user.is_authenticated %}
                    <input type="text" class="form-control" id="id_name" value="{{ user.first_name }}" disabled>
                    {% else %}
                    {{ form.name }}
                    {% endif %}
                    <label for="id_name">Имя</label>
                    {% if form.name.errors %}
                    <div id="id_name" class="invalid-feedback">
                        {% for error in form.name.errors %}
                        {{ error }}
                        {% endfor %}
                    </div>
                    {% endif %}
                </div>
            </div>
            <div class="col-lg-3">
                <div class="form-floating">
                    {% if user.is_authenticated %}
                    <input type="text" class="form-control" id="staticEmail" value="{{ user.email }}" disabled>
                    {% else %}
                    {{ form.email }}
                    {% endif %}
                    <label for="staticEmail">Email</label>
                    {% if form.email.errors %}
                    <div id="id_email" class="invalid-feedback">
                        {% for error in form.email.errors %}
                        {{ error }}
                        {% endfor %}
                    </div>
                    {% endif %}
                </div>
            </div>
            <div class="col-lg-3">
                <div class="form-floating">
                  {{ form.phone_number }}
                  <label for="id_phone_number">{{ form.phone_number.label}}</label>
                  {% if form.phone_number.errors %}
                  <div id="id_phone_number" class="invalid-feedback">
                      {% for error in form.phone_number.errors %}
                        {{ error }}
                      {% endfor %}
                  </div>
                  {% endif %}
                </div>
            </div>
        </div>
        <div class="row g-4 justify-content-center mb-3">
            <div class="col-lg-5">
                <div class="form-floating" data-url="{% url 'appointment:get_clinics' %}">
                    {{ form.clinic }}
                    <label for="id_clinic">{{ form.clinic.label }}</label>
                    {% if form.clinic.errors %}
                    <div id="id_clinic" class="invalid-feedback">
                        {% for error in form.clinic.errors %}
                        {{ error }}
                        {% endfor %}
                    </div>
                    {% endif %}
                </div>
            </div>
            <div class="col-lg-2">
                <div class="form-floating" data-url="{% url 'appointment:get_dates' %}">
                    {{ form.date}}
                    <label for="id_date">{{ form.date.label }}</label>
                    {% if form.date.errors %}
                    <div id="id_date" class="invalid-feedback">
                        {% for error in form.date.errors %}
                        {{ error }}
                        {% endfor %}
                    </div>
                    {% endif %}
                </div>
            </div>
            <div class="col-lg-2">
                <div class="form-floating" data-url="{% url 'appointment:get_timetable' %}">
                    {{ form.time}}
                    <label for="id_time">{{ form.time.label }}</label>
                    {% if form.time.errors %}
                    <div id="id_time" class="invalid-feedback">
                        {% for error in form.time.errors %}
                        {{ error }}
                        {% endfor %}
                    </div>
                    {% endif %}
                </div>
            </div>
        </div>
        <div class="row justify-content-center mb-3">
            <div class="col-lg-9">
                <div class="form-floating">
                    {{ form.description}}
                    <label for="id_description">{{ form.description.label }}</label>
                    {% if form.description.errors %}
                    <div id="id_description" class="invalid-feedback">
                        {% for error in form.description.errors %}
                        {{ error }}
                        {% endfor %}
                    </div>
                    {% endif %}
                </div>
            </div>
        </div>
        <div class="row justify-content-center mb-2">
            <div class="col-lg-9 d-grid gap-2">
                <button type="submit" class="btn btn-primary btn-lg">Записаться на прием</button>
            </div>
        </div>
        <div class="row justify-content-center text-center">
            <div class="col-lg-9">
                <div class="mb-2"><small class="text-muted">Все поля данной формы обязытельны для заполнения.</small></div>
                {% if user.is_authenticated %}
                <div class="mb-2"><small class="text-muted">Поля "Имя" и "Электронная почта" можно изменить в настройках профиля.</small></div>
                {% endif %}
            </div>
        </div>
    </form>
    {% for e in form.non_field_errors %}
    <div class="alert alert-danger">{{ e }}</div>
    {% endfor %}
</main>
{% endblock %}
{% load static %}

{% block script %}
<script type="module" src="{% static 'appointment/appointment.js' %}"></script>
{% endblock %}