orthodontist/appointment/urls.py
from django.urls import path
from . import views


app_name = 'appointment'
urlpatterns = [
    path('', views.AppointmentView.as_view(), name='index'),
    path('get_clinics/', views.get_clinics, name='get_clinics'),
    path('get_dates/', views.get_dates, name='get_dates'),
    path('get_timetable/', views.get_timetable, name='get_timetable'),
    path('<int:pk>/delete_appointment/', views.delete_appointment, name='delete_appointment'),
    path('get_clinics_for_map/', views.ClinicsForMap.as_view(), name='get_clinics_for_map'),
]

orthodontist/ask/urls.py
from django.urls import path
from . import views



app_name = 'ask'
urlpatterns = [
    path('', views.AskView.as_view(), name='index'),
    path('<int:pk>/', views.QuestionDetail.as_view(), name='question'),
    path('ask/', views.AskQuestionView.as_view(), name='ask_question'),
    path('<int:pk>/delete_question/', views.delete_question, name='delete_question'),
    path('<int:pk>/delete_answer/', views.delete_answer, name='delete_answer'),
    path('<int:pk>/like/', views.like_question, name='like'),
    path('ajax_sorting/', views.QuestionListAjax.as_view(), name='question_ajax'),
    path('<int:pk>/edit_question/', views.QuestionEdit.as_view(), name='edit_question'),
]

orthodontist/feedback/urls.py
from django.urls import path
from . import views


app_name = 'feedback'
urlpatterns = [
    path('', views.FeedbackView.as_view(), name='index'),
]

orthodontist/orthodontist/urls.py
from django.contrib import admin
from django.urls import path, include
from index import views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('about/', views.about, name='about'),
    path('admin/', admin.site.urls),
    path('question/', include('ask.urls')),
    path('appointment/', include('appointment.urls')),
    path('feedback/', include('feedback.urls')),
    path('signup/', views.signup, name='signup'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('user/<int:pk>/', views.UserView.as_view(), name='user'),
    path('user/<int:pk>/popular/', views.UserViewPopular.as_view(), name='user_popular'),
    path('user/<int:pk>/update/', views.UserViewUpdate.as_view(), name='update'),
    path('user/<int:pk>/appointments/', views.UserViewAppointments.as_view(), name='appointments'),
    path('search/', views.SearchResults.as_view(), name='search'),

]

if bool(settings.DEBUG):
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orthodontist/ask/models.py
from django.db import models
from django.contrib.auth.models import User


class QuestionManager(models.Manager):

    def annotated(self):
        queryset = self.extra(select={
            'answers_count': 'COALESCE((select count(*) from ask_question q join ask_answer a on q.id = a.question_id '
                             'where ask_question.id = q.id group by q.id), 0)',
            'like_count': 'COALESCE((select count(*) from ask_question q join ask_question_like l '
                          'on q.id = l.question_id where ask_question.id = q.id group by q.id), 0)'
        })
        return queryset


class Question(models.Model):
    text = models.CharField(max_length=1000, verbose_name='Текст вопроса')
    title = models.CharField(max_length=255, verbose_name='Заголовок вопроса')
    date = models.DateTimeField(auto_now_add=True, verbose_name='Дата')
    author = models.ForeignKey(User, null=True, on_delete=models.SET_NULL, verbose_name='Автор')
    like = models.ManyToManyField(User, related_name='question_to_like',
                                  verbose_name='Пользователи, которым нравится вопрос')
    objects = QuestionManager()


    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'вопрос'
        verbose_name_plural = 'вопросы'


class Answer(models.Model):
    text = models.CharField(max_length=1000, verbose_name='Текст ответа')
    date = models.DateTimeField(auto_now_add=True, verbose_name='Дата')
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    author = models.ForeignKey(User, null=True, on_delete=models.SET_NULL, verbose_name='Автор')

    def __str__(self):
        return self.text

    class Meta:
        verbose_name = 'ответ'
        verbose_name_plural = 'ответы'

orthodontist/index/forms.py
from django import forms
from django.utils import timezone
from django.contrib.auth import authenticate, login
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from datetime import timedelta
from .models import Profile


class ErrorClassMixin:

    def validation_error_class(self):
        for field in self:
            if field.errors:
                field.field.widget.attrs['class'] += ' is-invalid'


class SignupForm(ErrorClassMixin, UserCreationForm):
    remember_me = forms.BooleanField(widget=forms.CheckboxInput(attrs={'type': 'checkbox'}), label='Запомнить меня',
                                     required=False)

    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email', 'password1', 'password2']
        widgets = {
            'first_name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Имя*'}),
            'last_name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Фамилия'}),
            'email': forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'Email*'}),
        }

    def __init__(self, *args, **kwargs):
        super(SignupForm, self).__init__(*args, **kwargs)
        self.fields['password1'].widget.attrs['class'] = 'form-control'
        self.fields['password1'].widget.attrs['placeholder'] = 'Пароль*'
        self.fields['password2'].widget.attrs['class'] = 'form-control'
        self.fields['password2'].widget.attrs['placeholder'] = 'Повторите пароль*'

    def log_in(self, request, user):
        login(request, user)
        if self.cleaned_data['remember_me']:
            request.session.set_expiry(timedelta(days=30).total_seconds())
        else:
            request.session.set_expiry(0)

    def save(self, commit=True):
        user = super(SignupForm, self).save(commit=False)
        user.username = self.cleaned_data['first_name'] + str(timezone.now().timestamp().__trunc__())
        if commit:
            user.save()
        return user

    def clean_first_name(self):
        first_name = self.cleaned_data['first_name']
        if not first_name:
            raise forms.ValidationError('Обязательное поле.')
        return first_name

    def clean_email(self):
        email = self.cleaned_data['email']
        if not email:
            raise forms.ValidationError('Обязательное поле.')
        if email in User.objects.all().values_list('email', flat=True):
            raise forms.ValidationError('Пользователь с таким электронным адресом уже существует.')
        return email




class LoginForm(ErrorClassMixin ,forms.Form):

    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop('request', None)
        super(LoginForm, self).__init__(*args, **kwargs)

    email = forms.CharField(
        widget=forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'Электронная почта'}))
    password = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'type': 'password',
                                                             'placeholder': 'Пароль'}))
    remember_me = forms.BooleanField(widget=forms.CheckboxInput(attrs={'type': 'checkbox'}), label='Запомнить меня',
                                     required=False)

    def log_in(self, request):
        email = self.cleaned_data.get('email')
        password = self.cleaned_data.get('password')
        remember_me = self.cleaned_data.get('remember_me')
        user = authenticate(request, username=email, password=password)
        if user:
            login(request, user)
            if remember_me:
                request.session.set_expiry(timedelta(days=30).total_seconds())
            else:
                request.session.set_expiry(0)
            return True

    def clean(self):
        if not self.errors and not self.log_in(self.request):
            for field in self:
                if field.field.widget.attrs.get('class'):
                    field.field.widget.attrs['class'] += ' is-invalid'
            raise forms.ValidationError('Неверные логин или пароль.')


class UserUpdateForm(ErrorClassMixin, forms.ModelForm):

    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email']
        widgets = {
            'first_name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Имя'}),
            'last_name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Фамилия'}),
            'email': forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'Email'}),
        }

    def clean_first_name(self):
        first_name = self.cleaned_data['first_name']
        if not first_name:
            raise forms.ValidationError('Обязательное поле.')
        return first_name

    def clean_email(self):
        email = self.cleaned_data['email']
        if not email:
            raise forms.ValidationError('Обязательное поле.')
        return email


class ProfileUpdateForm(ErrorClassMixin, forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['image']
        labels = {
            "image": "Фото профиля"
        }
        widgets = {
            'image': forms.FileInput(attrs={'class': 'form-control'})
        }


SEARCH_OPTIONS = [
    ('default', 'заголовку и содержанию'),
    ('question_title', 'заголовку'),
    ('question_text', 'содержанию'),
    ('question_author', 'автору'),
]

ORDER_BY = [
    ('new', 'дате - сначала новые'),
    ('old', 'дате - сначала старые'),
    ('popular', 'популярности'),
    ('answers', 'обсуждаемости')
]


class SearchForm(forms.Form):
    search_input = forms.CharField(required=False, max_length=255, widget=forms.TextInput(
                                                        attrs={'class': 'form-control me-2', 'placeholder': 'Поиск'}),
                                   label='Ключевое слово')
    search_by = forms.ChoiceField(required=False, choices=SEARCH_OPTIONS,
                                  widget=forms.Select(attrs={'class': 'form-control'}), label='Искать по')
    order_by = forms.ChoiceField(required=False, choices=ORDER_BY,
                                 widget=forms.Select(attrs={'class': 'form-control'}), label='Сортировать по')

orthodontist/templates/index/index.html
{% extends "base.html" %}

{% block title %}Главная | {{ block.super }}{% endblock %}

{% load static %}

{% block content %}
<style>
    @media (min-width: 62em) {
      .featurette-heading {
        margin-top: 8rem;
      }
    }
    .text-start{
        min-height: 14rem;
    }
    .marketing .col-lg-4 {
      margin-bottom: 1.5rem;
      text-align: center;
    }
    .marketing h2 {
      font-weight: 400;
    }
    .marketing .col-lg-4 p {
      margin-right: .75rem;
      margin-left: .75rem;
    }
</style>

<main class="container mb-5">
    <div class="row featurette">
        <div class="col-md-5">
            <img src="{% static 'profile.png' %}" alt="">
        </div>
        <div class="col-md-7 pt-2">
            <h1 class="featurette-heading display-5 text-lg-start text-center">Екатерина Бахур</h1>
            <h2 class="text-muted display-6 text-lg-start text-center">стоматолог-ортодонт</h2>
            <p class="lead text-lg-start text-center">Оказание профессиональных ортодонтических услуг любой сложности с применением самых совеременных практик.</p>
            <div class="d-flex justify-content-center d-lg-inline-flex">
                <a class="btn btn-outline-primary btn-lg" href="{% url 'about' %}">О враче</a>
            </div>

        </div>
    </div>
    <div class="container marketing mt-5">
        <div class="row justify-content-center">
            <div class="col-lg-4">
                <img class="rounded-circle" width="140" height="140" src="{% static '3.png' %}" alt="">
                <h2>Опыт других<br>пациентов</h2>
                <p>На сайте собран опыт десятков пациентов, успешно завершивших свое лечение. Среди их вопросов может найтись решение Вашей проблемы</p>
                <p><a class="btn btn-outline-primary" href="{% url 'ask:index' %}">Все вопросы</a></p>
            </div>
            <div class="col-lg-4">
                <img class="rounded-circle" width="140" height="140" src="{% static '2.png' %}" alt="">
                <h2>Личный<br>кабинет</h2>
                <p>Создайте личный кабинет, через который Вы сможете легко управлять своими записями, задавать вопросы специалисту и оставлять отзывы</p>
                <p><a class="btn btn-outline-primary" href="{% if user.id %}{% url 'user' user.id %}{% else %}{% url 'signup' %}{% endif %}">Зарегистрироваться</a></p>
            </div>
            <div class="col-lg-4">
                <img class="rounded-circle" width="140" height="140" src="{% static '1.png' %}" alt="">
                <h2>Запишитесь<br>на прием</h2>
                <p>Если Вы уже изучили много информации в интернете, но до сих пор не знаете, куда двигаться, запишитесь на бесплатную консультацию</p>
                <p><a class="btn btn-outline-primary" href="{% url 'appointment:index' %}">Записаться</a></p>
            </div>
        </div>
    </div>
    <div class="row justify-content-center my-5">
        <div>
            <h3><a style="color: black; text-decoration: none;" href="{% url 'feedback:index' %}">Отзывы пациентов</a></h3>
        </div>
        <div id="myCarousel" class="carousel carousel-dark slide p-3" data-bs-ride="carousel">
            <div class="carousel-indicators">
                <button type="button" data-bs-target="#myCarousel" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
                <button type="button" data-bs-target="#myCarousel" data-bs-slide-to="1" aria-label="Slide 2"></button>
                <button type="button" data-bs-target="#myCarousel" data-bs-slide-to="2" aria-label="Slide 3"></button>
            </div>
            <div class="carousel-inner">
                <div class="carousel-item active">
                    <div class="text-start d-flex align-items-center">
                        <blockquote class="blockquote mx-5">
                            <p class="font-italic lead"> <i class="fa fa-quote-left mr-3 me-3 text-secondary"></i>
                                <em><a style="text-decoration: none;" class="text-dark" href="{% url 'feedback:index' %}">{{ feedback1.comment|truncatechars:380 }}</a></em>
                            </p>
                            <footer class="blockquote-footer mt-2">{{ feedback1.name }}, {{ feedback1.date|date:'j E o' }}
                            </footer>
                        </blockquote>
                    </div>
                </div>
                <div class="carousel-item">
                    <div class="text-start d-flex align-items-center">
                        <blockquote class="blockquote mx-5">
                            <p class="font-italic lead"> <i class="fa fa-quote-left mr-3 me-3 text-secondary"></i>
                                <em><a style="text-decoration: none;" class="text-dark" href="{% url 'feedback:index' %}">{{ feedback2.comment|truncatechars:380 }}</a></em>
                            </p>
                            <footer class="blockquote-footer mt-2">{{ feedback2.name }}, {{ feedback2.date|date:'j E o' }}
                            </footer>
                        </blockquote>
                    </div>
                </div>
                <div class="carousel-item">
                    <div class="text-start d-flex align-items-center">
                        <blockquote class="blockquote mx-5">
                            <p class="font-italic lead"> <i class="fa fa-quote-left mr-3 me-3 text-secondary"></i>
                                <em><a style="text-decoration: none;" class="text-dark" href="{% url 'feedback:index' %}">{{ feedback3.comment|truncatechars:380 }}</a></em>
                            </p>
                            <footer class="blockquote-footer mt-2">{{ feedback3.name }}, {{ feedback3.date|date:'j E o' }}
                            </footer>
                        </blockquote>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="mb-4">
            <h3 id="make-appointment"><a style="color: black; text-decoration: none;" href="{% url 'appointment:index' %}">Запись на прием</a></h3>
        </div>
        <div class="col-lg-7">
            <form method="post" class="needs-validation" action="{% url 'appointment:index' %}" novalidate>
                {% csrf_token %}
                <div class="row g-4 mb-3">
                    <div class="col-lg-4">
                        <div class="form-floating">
                            {% if user.is_authenticated %}
                            <input type="text" class="form-control" id="id_name" value="{{ user.first_name }}" disabled>
                            {% else %}
                            {{ form.name }}
                            {% endif %}
                            <label for="id_name">Имя</label>
                        </div>
                    </div>
                    <div class="col-lg-4">
                        <div class="form-floating">
                            {% if user.is_authenticated %}
                            <input type="text" class="form-control" id="staticEmail" value="{{ user.email }}" disabled>
                            {% else %}
                            {{ form.email }}
                            {% endif %}
                            <label for="staticEmail">Email</label>
                        </div>
                    </div>
                    <div class="col-lg-4">
                        <div class="form-floating">
                          {{ form.phone_number }}
                          <label for="id_phone_number">{{ form.phone_number.label}}</label>
                        </div>
                    </div>
                </div>
                <div class="row g-4 mb-3">
                    <div class="col-lg-6">
                        <div class="form-floating" data-url="{% url 'appointment:get_clinics' %}">
                            {{ form.clinic }}
                            <label for="id_clinic">{{ form.clinic.label }}</label>
                        </div>
                    </div>
                    <div class="col-lg-3">
                        <div class="form-floating" data-url="{% url 'appointment:get_dates' %}">
                            {{ form.date}}
                            <label for="id_date">{{ form.date.label }}</label>
                        </div>
                    </div>
                    <div class="col-lg-3">
                        <div class="form-floating" data-url="{% url 'appointment:get_timetable' %}">
                            {{ form.time}}
                            <label for="id_time">{{ form.time.label }}</label>
                        </div>
                    </div>
                </div>
                <div class="row mb-4">
                    <div class="col-lg">
                        <div class="form-floating">
                            {{ form.description}}
                            <label for="id_description">{{ form.description.label }}</label>
                        </div>
                    </div>
                </div>
                <div class="row mb-3">
                    <div class="col-lg-12 d-grid gap-2">
                        <button type="submit" class="btn btn-primary btn-lg">Записаться на прием</button>
                    </div>
                </div>
            </form>
        </div>
        <div class="col-lg-5">
            <p style="line-height: 1.2;"><small class="text-muted">Клиники, в которых можно воспользоваться услагами Екатерины, расположены в удобных локациях города Краснодара. Выберите удобную для Вас на карте:</small></p>
            <div class="ratio ratio-16x9 justify-content-center">
                <div id="map"></div>
            </div>
        </div>
    </div>
</main>
{% endblock %}

{% load static %}

{% block script %}
<script src="{% static 'appointment/appointment.js' %}" type="module"></script>
<script src="https://api-maps.yandex.ru/2.1/?lang=ru_RU&amp;apikey=b5d82f06-3c11-495e-8461-74b818294a04" type="text/javascript"></script>
<script src="{% static 'index/maps.js' %}" type="text/javascript"></script>
{% endblock %}

orthodontist/templates/index/user.html
{% extends "user_base.html" %}
{% block user_questions %}
            <div class="mb-3">
                <h5>Последние вопросы от пользователя {{ userdata.first_name }}</h5>
            </div>
            {% if userdata.question_set.all %}
            {% for question in page_obj %}
            <div class="card mb-2">
                <div class="card-body">
                    <h6 class="card-subtitle mb-2 text-muted">Дата: {{ question.date|date:'j E o' }}</h6>
                    <h6 class="card-subtitle mb-2 text-muted">Ответы: {{ question.answers_count }}</h6>
                    <h5 class="card-title"><a style="color: black; text-decoration: none;" href="{% url 'ask:question' question.id %}">{{ question.title }}</a></h5>
                    <p class="card-text support-line-breaks">{{ question.text|truncatechars:100 }}</p>
                    <button class="like-btn btn btn-sm btn-primary {% if user in question.like.all %}active{% endif %} float-end" type="submit" data-url="{% url 'ask:like' question.id %}" data-qid="{{question.id}}"><i class="far fa-thumbs-up"></i> <span class="like_count">{{ question.like.count }}</span></button>
                </div>
            </div>
            {% endfor %}
            {% if page_obj.paginator.num_pages > 1 %}
            <nav>
                <ul class="pagination justify-content-center">
                    {% if page_obj.has_previous %}
                    <li class="page-item">
                        <a class="page-link text-primary" href="?page=1">Первая</a>
                    </li>
                    {% if page_obj.number|add:'-2' > 0 %}
                    <li class="page-item">
                        <a class="page-link text-primary" href="?page={{ page_obj.number|add:'-2' }}">{{ page_obj.number|add:'-2' }}</a>
                    </li>
                    {% endif %}
                    <li class="page-item">
                        <a class="page-link text-primary" href="?page={{ page_obj.previous_page_number }}">{{ page_obj.previous_page_number }}</a>
                    </li>
                    {% else %}
                    <li class="page-item disabled">
                        <a class="page-link text-primary" href="#" disabled>Первая</a>
                    </li>
                    {% endif %}
                    <li class="page-item active">
                        <span class="page-link bg-primary">{{ page_obj.number }}</span>
                    </li>
                    {% if page_obj.has_next %}
                    <li class="page-item">
                        <a class="page-link text-primary" href="?page={{ page_obj.next_page_number }}">{{ page_obj.next_page_number }}</a>
                    </li>
                    {% if page_obj.number|add:'2' <= page_obj.paginator.num_pages %}
                    <li class="page-item">
                        <a class="page-link text-primary" href="?page={{ page_obj.number|add:'2' }}">{{ page_obj.number|add:'2' }}</a>
                    </li>
                    {% endif %}
                    <li class="page-item">
                        <a class="page-link text-primary" href="?page={{ page_obj.paginator.num_pages }}">Последняя</a>
                    </li>
                    {% else %}
                    <li class="page-item disabled">
                        <a class="page-link text-primary" href="#">Последняя</a>
                    </li>
                    {% endif %}
                </ul>
            </nav>
            {% endif %}
            {% else %}
            <p>Пользователь {{ userdata.first_name }} пока не задавал вопросы.</p>
            {% endif %}
{% endblock %}

orthodontist/templates/index/user_appointments.html
{% extends "user_base.html" %}
{% block user_questions %}
                    <div class="mb-3">
                        <h5>Записи на прием</h5>
                    </div>
                    {% if future_appointments %}
                    {% for appointment in future_appointments %}
                    <div class="card mb-2">
                        <div class="card-body">
                            <h6 class="card-title mb-3">Прием в клинике "{{ appointment.clinic }}"</h6>
                            <h6 class="card-subtitle mb-2 text-muted">Дата приема: {{ appointment.date }}</h6>
                            <h6 class="card-subtitle mb-2 text-muted">Время приема: {{ appointment.time }}</h6>
                            <a href="{% url 'appointment:delete_appointment' appointment.id %}" class="btn btn-primary btn-sm mt-2">Отменить запись</a>
                        </div>
                    </div>
                    {% endfor %}
                    {% else %}
                    <dev>У вас пока нет предстоящих записей на прием. Вы можете записаться <a href="{% url 'appointment:index' %}">здесь</a>.</dev>
                    {% endif %}

                    <div class="my-3">
                        <h5>Состоявшиеся приемы</h5>
                    </div>
                    {% if past_appointments %}
                    {% for appointment in past_appointments %}
                    <div class="card">
                        <div class="card-body">
                            <h6 class="card-title mb-3">Прием в клинике "{{ appointment.clinic }}"</h6>
                            <h6 class="card-subtitle mb-2 text-muted">Дата приема: {{ appointment.date }}</h6>
                            <h6 class="card-subtitle mb-2 text-muted">Время приема: {{ appointment.time }}</h6>
                            <a href="{% url 'feedback:index' %}?appointment={{ appointment.id }}" class="btn btn-primary btn-sm mt-2">Оставить отзыв</a>
                        </div>
                    </div>
                    {% endfor %}
                    {% else %}
                    <dev>У вас пока нет состоявшихся приемов.</dev>
                    {% endif %}
{% endblock %}

orthodontist/templates/index/user_popular.html
{% extends "user_base.html" %}
{% block user_questions %}
            <div class="mb-3">
                <h5>Популярные вопросы пользователя {{ userdata.first_name }}</h5>
            </div>
            {% if userdata.question_set.all %}
            {% for question in page_obj %}
            <div class="card mb-2">
                <div class="card-body">
                    <h6 class="card-subtitle mb-2 text-muted">Дата: {{ question.date|date:'j E o' }}</h6>
                    <h6 class="card-subtitle mb-2 text-muted">Ответы: {{ question.answers_count }}</h6>
                    <h5 class="card-title"><a style="color: black; text-decoration: none;" href="{% url 'ask:question' question.id %}">{{ question.title }}</a></h5>
                    <p class="card-text support-line-breaks">{{ question.text|truncatechars:100 }}</p>
                    <button class="like-btn btn btn-sm btn-primary {% if user in question.like.all %}active{% endif %} float-end" type="submit" data-url="{% url 'ask:like' question.id %}" data-qid="{{question.id}}"><i class="far fa-thumbs-up"></i> <span class="like_count">{{ question.like.count }}</span></button>
                </div>
            </div>
            {% endfor %}
            {% if page_obj.paginator.num_pages > 1 %}
            <nav>
                <ul class="pagination justify-content-center">
                    {% if page_obj.has_previous %}
                    <li class="page-item">
                        <a class="page-link text-primary" href="?page=1">Первая</a>
                    </li>
                    {% if page_obj.number|add:'-2' > 0 %}
                    <li class="page-item">
                        <a class="page-link text-primary" href="?page={{ page_obj.number|add:'-2' }}">{{ page_obj.number|add:'-2' }}</a>
                    </li>
                    {% endif %}
                    <li class="page-item">
                        <a class="page-link text-primary" href="?page={{ page_obj.previous_page_number }}">{{ page_obj.previous_page_number }}</a>
                    </li>
                    {% else %}
                    <li class="page-item disabled">
                        <a class="page-link text-primary" href="#" disabled>Первая</a>
                    </li>
                    {% endif %}
                    <li class="page-item active">
                        <span class="page-link bg-primary">{{ page_obj.number }}</span>
                    </li>
                    {% if page_obj.has_next %}
                    <li class="page-item">
                        <a class="page-link text-primary" href="?page={{ page_obj.next_page_number }}">{{ page_obj.next_page_number }}</a>
                    </li>
                    {% if page_obj.number|add:'2' <= page_obj.paginator.num_pages %}
                    <li class="page-item">
                        <a class="page-link text-primary" href="?page={{ page_obj.number|add:'2' }}">{{ page_obj.number|add:'2' }}</a>
                    </li>
                    {% endif %}
                    <li class="page-item">
                        <a class="page-link text-primary" href="?page={{ page_obj.paginator.num_pages }}">Последняя</a>
                    </li>
                    {% else %}
                    <li class="page-item disabled">
                        <a class="page-link text-primary" href="#">Последняя</a>
                    </li>
                    {% endif %}
                </ul>
            </nav>
            {% endif %}
            {% else %}
            <p>Пользователь {{ userdata.first_name }} пока не задавал вопросы.</p>
            {% endif %}
{% endblock %}