orthodontist/appointment/urls.py
from django.urls import path
from . import views


app_name = 'appointment'
urlpatterns = [
    path('', views.AppointmentView.as_view(), name='index'),
    path('get_clinics/', views.get_clinics, name='get_clinics'),
    path('get_dates/', views.get_dates, name='get_dates'),
    path('get_timetable/', views.get_timetable, name='get_timetable'),
    path('<int:pk>/delete_appointment/', views.delete_appointment, name='delete_appointment'),
    path('get_clinics_for_map/', views.ClinicsForMap.as_view(), name='get_clinics_for_map'),
]

orthodontist/ask/urls.py
from django.urls import path
from . import views



app_name = 'ask'
urlpatterns = [
    path('', views.AskView.as_view(), name='index'),
    path('<int:pk>/', views.QuestionDetail.as_view(), name='question'),
    path('ask/', views.AskQuestionView.as_view(), name='ask_question'),
    path('<int:pk>/delete_question/', views.delete_question, name='delete_question'),
    path('<int:pk>/delete_answer/', views.delete_answer, name='delete_answer'),
    path('<int:pk>/like/', views.like_question, name='like'),
    path('ajax_sorting/', views.QuestionListAjax.as_view(), name='question_ajax'),
    path('<int:pk>/edit_question/', views.QuestionEdit.as_view(), name='edit_question'),
]

orthodontist/feedback/urls.py
from django.urls import path
from . import views


app_name = 'feedback'
urlpatterns = [
    path('', views.FeedbackView.as_view(), name='index'),
]

orthodontist/orthodontist/urls.py
from django.contrib import admin
from django.urls import path, include
from index import views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('about/', views.about, name='about'),
    path('admin/', admin.site.urls),
    path('question/', include('ask.urls')),
    path('appointment/', include('appointment.urls')),
    path('feedback/', include('feedback.urls')),
    path('signup/', views.signup, name='signup'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('user/<int:pk>/', views.UserView.as_view(), name='user'),
    path('user/<int:pk>/popular/', views.UserViewPopular.as_view(), name='user_popular'),
    path('user/<int:pk>/update/', views.UserViewUpdate.as_view(), name='update'),
    path('user/<int:pk>/appointments/', views.UserViewAppointments.as_view(), name='appointments'),
    path('search/', views.SearchResults.as_view(), name='search'),

]

if bool(settings.DEBUG):
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orthodontist/ask/models.py
from django.db import models
from django.contrib.auth.models import User


class QuestionManager(models.Manager):

    def annotated(self):
        queryset = self.extra(select={
            'answers_count': 'COALESCE((select count(*) from ask_question q join ask_answer a on q.id = a.question_id '
                             'where ask_question.id = q.id group by q.id), 0)',
            'like_count': 'COALESCE((select count(*) from ask_question q join ask_question_like l '
                          'on q.id = l.question_id where ask_question.id = q.id group by q.id), 0)'
        })
        return queryset


class Question(models.Model):
    text = models.CharField(max_length=1000, verbose_name='Текст вопроса')
    title = models.CharField(max_length=255, verbose_name='Заголовок вопроса')
    date = models.DateTimeField(auto_now_add=True, verbose_name='Дата')
    author = models.ForeignKey(User, null=True, on_delete=models.SET_NULL, verbose_name='Автор')
    like = models.ManyToManyField(User, related_name='question_to_like',
                                  verbose_name='Пользователи, которым нравится вопрос')
    objects = QuestionManager()


    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'вопрос'
        verbose_name_plural = 'вопросы'


class Answer(models.Model):
    text = models.CharField(max_length=1000, verbose_name='Текст ответа')
    date = models.DateTimeField(auto_now_add=True, verbose_name='Дата')
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    author = models.ForeignKey(User, null=True, on_delete=models.SET_NULL, verbose_name='Автор')

    def __str__(self):
        return self.text

    class Meta:
        verbose_name = 'ответ'
        verbose_name_plural = 'ответы'

orthodontist/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
    {% load static %}
    <link href="{% static 'main.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.3/css/all.css" integrity="sha384-SZXxX4whJ79/gErwcOYf+zWLeJdY/qpuqC4cAa9rOGUstPomtqpuNWT9wdPEn2fk" crossorigin="anonymous">
    <title>{% block title %}Вопрос ортодонту{% endblock %}</title>
</head>
<body class="d-flex flex-column min-vh-100">
    <header>
        <nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top">
            <div class="container-fluid">
                <a class="navbar-brand" href="/">Вопрос ортодонту</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarCollapse">
                    <ul class="navbar-nav align-items-lg-center">
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown1" role="button" data-bs-toggle="dropdown" aria-expanded="false" href="#">Врач</a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown1">
                                <li><a class="dropdown-item" href="{% url 'about' %}">О враче</a></li>
                                <li><a class="dropdown-item" href="{% url 'appointment:index' %}">Запись на прием</a></li>
                                <li><a class="dropdown-item" href="{% url 'feedback:index' %}">Отзывы пациентов</a></li>
                            </ul>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown2" role="button" data-bs-toggle="dropdown" aria-expanded="false" href="#">Вопросы</a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown2">
                                <li><a class="dropdown-item" href="{% url 'ask:index' %}">Все вопроcы</a></li>
                                <li><a class="dropdown-item" href="{% url 'ask:ask_question' %}">Задать вопрос</a></li>
                            </ul>
                        </li>
                    </ul>
                    <ul class="navbar-nav ms-auto align-items-lg-center">
                        <form class="d-flex" action="{% url 'search' %}">
                            {{ searchform.search_input }}
                            <button class="btn btn-outline-primary" type="submit">Поиск</button>
                        </form>
                        {% if user.is_authenticated %}
                        <li class="nav-item dropdown me-2">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown3" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            Привет, {{ user.first_name }}
                            </a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown3">
                                <li><a class="dropdown-item" href="{% url 'user' user.id %}">Кабинет <i class="fas fa-user-circle"></i></a></li>
                                <li><hr class="dropdown-divider"></li>
                                <li><a class="dropdown-item" href="{% url 'logout' %}">Выйти <i class="fas fa-sign-out-alt"></i></a></li>
                            </ul>
                        </li>
                        {% else %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'signup' %}">Зарегистрироваться</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'login' %}">Войти <i class="fas fa-sign-in-alt"></i></a>
                        </li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    {% block content %}{% endblock %}
    <footer class="text-center text-lg-start bg-light text-muted mt-auto">
        <section class="p-2">
            <div class="container text-center text-md-start mt-3">
                <div class="row mt-3">
                    <div class="col-md-3 col-lg-4 col-xl-3 mx-auto mb-4">
                        <h6 class="text-uppercase fw-bold mb-4">Вопрос ортодонту</h6>
                        <p>Сайт стоматолога-ортодонта </br><a class="text-reset" href="{% url 'about' %}">Екатерины Бахур</a></p>
                    </div>
                    <div class="col-md-2 col-lg-2 col-xl-2 mx-auto mb-4">
                        <p><a href="{% url 'ask:index' %}" class="text-reset">Все вопросы</a></p>
                        <p><a href="{% url 'ask:ask_question' %}" class="text-reset">Задать вопрос</a></p>
                        <p><a href="{% url 'search' %}?search_input=" class="text-reset">Поиск по вопросам</a></p>
                    </div>
                    <div class="col-md-2 col-lg-2 col-xl-2 mx-auto mb-4">
                        <p><a href="{% if user.id %}{% url 'user' user.id %}{% else %}{% url 'login' %}{% endif %}" class="text-reset">Личный кабинет</a></p>
                        <p><a href="{% url 'appointment:index' %}" class="text-reset">Записаться на прием</a></p>
                        <p><a href="{% url 'feedback:index' %}" class="text-reset">Оставить отзыв</a></p>
                    </div>
                    <div class="col-md-4 col-lg-3 col-xl-3 mx-auto mb-md-0 mb-4">
                        <p><a href="mailto:orthodental@tut.by" class="text-reset text-decoration-none"><i class="fas fa-envelope me-3"></i>orthodental@tut.by</a></p>
                        <p><i class="fas fa-phone me-3"></i></i>+79181234567</p>
                        <p><a href="#" class="text-reset text-decoration-none"><i class="fab fa-telegram me-3"></i></i>@YourOrthodontistBot</a></p>
                    </div>
                </div>
            </div>
        </section>
        <div class="text-center p-2" style="background-color: rgba(0, 0, 0, 0.05);">© 2021 Copyright: Роман Шелемех</div>
    </footer>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js" integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0" crossorigin="anonymous"></script>
    {% block script %}{% endblock %}
</body>
</html>

orthodontist/templates/user_base.html
{% extends "base.html" %}

{% block title %} Мой профиль | {{ block.super }}{% endblock %}

{% block content %}
<main class="container mb-5">

    <div class="row p-3 m-3 mb-5 align-items-center border-bottom">
        <div class="col-md-2 d-flex justify-content-center mb-3">
            <div  class="user-pic-question">
                <img src="{{ userdata.profile.image.url }}" alt="profile-pic">
            </div>
        </div>
        <div class="col-md-3 text-lg-start text-center mb-3">
            <h3>{{ userdata.first_name }} {{ userdata.last_name }}</h3>
            <small class="text-muted">
                {% if userdata.profile.online %}
                Сейчас на сайте
                {% else %}
                {% if userdata.profile.last_seen %}
                Заходил(-a) {{ userdata.profile.last_seen|timesince }} назад
                {% else %}
                Заходил(-a) давно
                {% endif %}
                {% endif %}
            </small>
        </div>
        <div class="col-md-3 text-lg-start text-center">
            <small class="text-muted"><i class="far fa-question-circle"></i> Вопросы: {{ userdata.question_set.all.count }}</small>
        </div>
        <div class="col-md-3 text-lg-start text-center">
            <small class="text-muted"><i class="fas fa-award"></i> Репутация: {{ rating }}</small>
        </div>
        {% if userdata.is_superuser %}
        <div class="col-md-1 ms-md-auto d-flex justify-content-center">
            <a class="btn btn-outline-primary btn-sm mt-3" href="{% url 'admin:index' %}" role="button"><i class="fas fa-user-cog"></i></a>
        </div>
        {% endif %}
    </div>
    <div class="row">
        <div class="col col-lg-3">
            <nav class="nav flex-column  border-bottom me-4">
                <a class="nav-link" href="{% url 'user' userdata.id %}">Последние вопросы</a>
                <a class="nav-link" href="{% url 'user_popular' userdata.id %}">Популярные вопросы</a>
                {% if user == userdata %}
                <a class="nav-link" href="{% url 'appointments' userdata.id %}">Записи на прием</a>
                <a class="nav-link" href="{% url 'update' userdata.id %}">Настройки</a>
                {% endif %}
            </nav>
            <div class="mt-3 text-lg-start text-center"><small class="text-muted">ID пользователя: {{ userdata.id }}</small></div>
            <div class="mt-2 mb-4 text-lg-start text-center"><small class="text-muted">Присоединился {{ userdata.date_joined.date|date:'j E o' }}</small></div>
        </div>
        <div class="col-lg-9">
            {% if messages %}
            {% for message in messages %}
            <div class="alert alert-success" role="alert">{{ message }}</div>
            {% endfor %}
            {% endif %}
            {% block user_questions %}{% endblock %}
        </div>
    </div>
</main>
{% endblock %}
{% load static %}
{% block script %}
<script type="module" src="{% static 'index/user.js' %}"></script>
{% endblock %}