orthodontist/ask/urls.py
from django.urls import path
from . import views



app_name = 'ask'
urlpatterns = [
    path('', views.AskView.as_view(), name='index'),
    path('<int:pk>/', views.QuestionDetail.as_view(), name='question'),
    path('ask/', views.AskQuestionView.as_view(), name='ask_question'),
    path('<int:pk>/delete_question/', views.delete_question, name='delete_question'),
    path('<int:pk>/delete_answer/', views.delete_answer, name='delete_answer'),
    path('<int:pk>/like/', views.like_question, name='like'),
    path('ajax_sorting/', views.QuestionListAjax.as_view(), name='question_ajax'),
    path('<int:pk>/edit_question/', views.QuestionEdit.as_view(), name='edit_question'),
]

orthodontist/orthodontist/urls.py
from django.contrib import admin
from django.urls import path, include
from index import views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('about/', views.about, name='about'),
    path('admin/', admin.site.urls),
    path('question/', include('ask.urls')),
    path('appointment/', include('appointment.urls')),
    path('feedback/', include('feedback.urls')),
    path('signup/', views.signup, name='signup'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('user/<int:pk>/', views.UserView.as_view(), name='user'),
    path('user/<int:pk>/popular/', views.UserViewPopular.as_view(), name='user_popular'),
    path('user/<int:pk>/update/', views.UserViewUpdate.as_view(), name='update'),
    path('user/<int:pk>/appointments/', views.UserViewAppointments.as_view(), name='appointments'),
    path('search/', views.SearchResults.as_view(), name='search'),

]

if bool(settings.DEBUG):
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orthodontist/ask/models.py
from django.db import models
from django.contrib.auth.models import User


class QuestionManager(models.Manager):

    def annotated(self):
        queryset = self.extra(select={
            'answers_count': 'COALESCE((select count(*) from ask_question q join ask_answer a on q.id = a.question_id '
                             'where ask_question.id = q.id group by q.id), 0)',
            'like_count': 'COALESCE((select count(*) from ask_question q join ask_question_like l '
                          'on q.id = l.question_id where ask_question.id = q.id group by q.id), 0)'
        })
        return queryset


class Question(models.Model):
    text = models.CharField(max_length=1000, verbose_name='Текст вопроса')
    title = models.CharField(max_length=255, verbose_name='Заголовок вопроса')
    date = models.DateTimeField(auto_now_add=True, verbose_name='Дата')
    author = models.ForeignKey(User, null=True, on_delete=models.SET_NULL, verbose_name='Автор')
    like = models.ManyToManyField(User, related_name='question_to_like',
                                  verbose_name='Пользователи, которым нравится вопрос')
    objects = QuestionManager()


    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'вопрос'
        verbose_name_plural = 'вопросы'


class Answer(models.Model):
    text = models.CharField(max_length=1000, verbose_name='Текст ответа')
    date = models.DateTimeField(auto_now_add=True, verbose_name='Дата')
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    author = models.ForeignKey(User, null=True, on_delete=models.SET_NULL, verbose_name='Автор')

    def __str__(self):
        return self.text

    class Meta:
        verbose_name = 'ответ'
        verbose_name_plural = 'ответы'

orthodontist/ask/forms.py
from django import forms
from .models import Question, Answer
from django.urls import reverse
from index.forms import ErrorClassMixin


class AskQuestionForm(ErrorClassMixin, forms.ModelForm):
    class Meta:
        model = Question
        fields = ['title', 'text']
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Вопрос кратко'}),
            'text': forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Подробное изложение вопроса',
                                          'style': 'height: 180px'}),
        }
        labels = {
            'title': 'Вопрос кратко',
            'text': 'Подробное изложение вопроса'
        }

    def save(self, commit=True):
        question = Question(**self.cleaned_data)
        question.save()
        return question


class ReplyForm(forms.ModelForm):
    class Meta:
        model = Answer
        fields = ['text']
        widgets = {
            'text': forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Ваш ответ'}),
        }
        labels = {
            'text': 'Ответ'
        }

    def save(self, commit=True):
        answer = Answer(**self.cleaned_data)
        answer.save()
        return answer


ORDER_BY = [
    ('new', 'дате - сначала новые'),
    ('old', 'дате - сначала старые'),
    ('popular', 'популярности'),
    ('answers', 'обсуждаемости')
]


class OrderByForm(forms.Form):
    order_by = forms.ChoiceField(required=False, choices=ORDER_BY, label='Сортировать по',
                                 widget=forms.Select(attrs={'class': 'form-control'}))


class QuestionEditForm(forms.ModelForm):

    class Meta:
        model = Question
        fields = ['title', 'text']
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Вопрос кратко'}),
            'text': forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Подробное изложение вопроса'}),
        }
        labels = {
            'title': 'Заголовок',
            'text': 'Вопрос'
        }

orthodontist/ask/views.py
from django.urls import reverse
from django.http import HttpResponseRedirect, Http404, JsonResponse
from django.shortcuts import get_object_or_404
from django.views.generic import DetailView, TemplateView
from django.views.generic.edit import FormView
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.utils.decorators import method_decorator
from .models import Question, Answer
from .forms import AskQuestionForm, ReplyForm, OrderByForm
from rest_framework import generics
from rest_framework.generics import UpdateAPIView
from .serializers import QuestionSerializer, QuestionEditSerializer
from .permissions import IsOwnerOrReadOnly


class AskView(TemplateView):
    template_name = 'ask/index.html'

    def dispatch(self, request, *args, **kwargs):
        self.form = OrderByForm(request.GET)
        self.form.is_valid()
        return super(AskView, self).dispatch(request, *args, **kwargs)

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(AskView, self).get_context_data(**kwargs)
        context['form'] = self.form
        return context


class QuestionDetail(DetailView):
    model = Question
    template_name = 'ask/question.html'
    context_object_name = 'question'

    def dispatch(self, request, *args, **kwargs):
        self.form = ReplyForm()
        return super(QuestionDetail, self).dispatch(request, *args, **kwargs)

    def post(self, request, **kwargs):
        form = ReplyForm(request.POST)
        if form.is_valid():
            form.cleaned_data['question'] = self.get_object()
            form.cleaned_data['author'] = request.user
            form.save()
            return HttpResponseRedirect(reverse('ask:question', args=(kwargs['pk'],)))

    def get_context_data(self, **kwargs):
        context = super(QuestionDetail, self).get_context_data(**kwargs)
        context['reply_form'] = self.form
        return context


@method_decorator(login_required, name='dispatch')
class AskQuestionView(FormView):
    template_name = 'ask/ask_question.html'
    form_class = AskQuestionForm

    def get_success_url(self):
        return reverse('ask:index')

    def form_valid(self, form):
        form.cleaned_data['author'] = self.request.user
        form.save()
        return super().form_valid(form)
    
    def form_invalid(self, form):
        form.validation_error_class()
        return super(AskQuestionView, self).form_invalid(form)

def delete_question(request, pk):
    question = get_object_or_404(Question, pk=pk)
    if request.user == question.author:
        _, deleted = question.delete()
        messages.success(
            request, f'Вопрос "{question.title}" и все ответы на него ({deleted.get("ask.Answer", "0")}) '
                     f'были успешно удалены'
        )
        return HttpResponseRedirect(reverse('ask:index'))
    else:
        raise Http404()


def delete_answer(request, pk):
    answer = get_object_or_404(Answer, pk=pk)
    if request.user == answer.author:
        answer.delete()
        messages.success(request, f'Ответ был успешно удален')
        return HttpResponseRedirect(reverse('ask:question', args=[answer.question.id]))
    else:
        raise Http404()


def like_question(request, pk):
    if request.is_ajax():
        user = request.user
        if user.is_authenticated:
            question = get_object_or_404(Question, pk=pk)
            if user not in question.like.all():
                question.like.add(user)
                add = True
            else:
                question.like.remove(user)
                add = False
            like_count = question.like.count()
            return JsonResponse({'like_count': like_count, 'add': add})
        else:
            return JsonResponse({'auth': '/login/?next=/question/'})
    else:
        raise Http404()


class QuestionListAjax(generics.ListAPIView):
    serializer_class = QuestionSerializer

    def initial(self, request, *args, **kwargs):
        if not request.is_ajax():
            raise Http404()
        return super(QuestionListAjax, self).initial(request, *args, **kwargs)

    def get_queryset(self):
        order_by = self.request.GET.get('order_by')
        queryset = Question.objects.annotated()
        if not order_by or order_by == 'new':
            queryset = queryset.order_by('-date')
        elif order_by == 'old':
            queryset = queryset.order_by('date')
        elif order_by == 'popular':
            queryset = queryset.order_by('-like_count')
        elif order_by == 'answers':
            queryset = queryset.order_by('-answers_count')
        return queryset
    
    def get_serializer_context(self):
        context = super(QuestionListAjax, self).get_serializer_context()
        context['user'] = self.request.user
        return context


class QuestionEdit(UpdateAPIView):
    serializer_class = QuestionEditSerializer
    queryset = Question.objects.all()
    permission_classes = [IsOwnerOrReadOnly]

    def initial(self, request, *args, **kwargs):
        if not request.is_ajax():
            raise Http404()
        return super(QuestionEdit, self).initial(request, *args, **kwargs)

orthodontist/templates/ask/ask_question.html
{% extends "base.html" %}

{% block title %}Задать вопрос | {{ block.super }}{% endblock %}

{% block content %}
<main class="container mb-5">
    <div class="row justify-content-center">
        <div class="col-lg-9 mb-3">
            <h2>Задайте свой вопрос</h2>
        </div>
    </div>
    <div class="row justify-content-center">
        <div class="col-lg-9">
            <form method="post" class="needs-validation" novalidate>
                {% csrf_token %}
                <div class="form-floating mb-3">
                    {{ form.title }}
                    <label for="id_title">{{ form.title.label}}</label>
                    {% if form.title.errors %}
                    <div id="id_title" class="invalid-feedback">
                    {% for error in form.title.errors %}
                    {{ error }}
                    {% endfor %}
                    </div>
                    {% endif %}
                </div>
                <div class="form-floating mb-3">
                    {{ form.text }}
                    <label for="id_title">{{ form.text.label}}</label>
                    {% if form.text.errors %}
                    <div id="id_text" class="invalid-feedback">
                    {% for error in form.text.errors %}
                    {{ error }}
                    {% endfor %}
                    </div>
                    {% endif %}
                </div>
                <input class="btn btn-primary" type="submit" value="Задать вопрос">
            </form>
        </div>
    </div>

</main>
{% endblock %}

orthodontist/templates/ask/index.html
{% extends "base.html" %}

{% block title %}Вопросы | {{ block.super }}{% endblock %}

{% block content %}
<main class="container mb-5">
    <div class="row justify-content-center">
        <div class="col-lg-9 mb-3">
            <h2>Вопросы ортодонту</h2>
        </div>
    </div>
    <div class="row justify-content-center">
        <div class="col-lg-9">
            {% if messages %}
            {% for message in messages %}
            <div class="alert alert-success" role="alert">{{ message }}</div>
            {% endfor %}
            {% endif %}
        </div>
    </div>
    <form>
        <div class="row justify-content-center align-items-center g-2">
            <div class="col-auto">Сортировать по</div>
            <div class="col-auto">{{ form.order_by }}</div>
        </div>
    </form>
    <div id="question-list" class="min-vh-100" data-url="{% url 'ask:question_ajax' %}"></div>
    <div id="spinner"></div>
    <nav>
        <ul class="pagination justify-content-center" id="pagination"></ul>
    </nav>
</main>
{% endblock %}
{% load static %}
{% block script %}
<script type="module" src="{% static 'ask/index.js' %}"></script>
{% endblock %}

orthodontist/templates/ask/question.html
{% extends "base.html" %}

{% block title %} {{question }} | {{ block.super }}{% endblock %}

{% block content %}
<main class="container mb-5">
    {% if messages %}
    {% for message in messages %}
    <div class="alert alert-success" role="alert">{{ message }}</div>
    {% endfor %}
    {% endif %}
    <div class="row justify-content-center my-3">
        <div class="col-sm col-md-10">
            <div class="card">
                <div class="card-body">
                   <div class="clearfix">
                       {% if user.id == question.author.id %}
                       <a href="{% url 'ask:delete_question' question.id %}" class="float-end" style="color:gray" onclick="return confirm('Вы уверены?');"><i class="far fa-trash-alt"></i></a>
                       <a href="#" data-url="{% url 'ask:edit_question' question.id %}" class="float-end me-2" style="color:gray" id="edit-button"><i class="far fa-edit"></i></a>
                       {% endif %}
                       <div class="user-pic-question float-start mb-3">
                           <img src="{{ question.author.profile.image.url }}" alt="{{ question.author.first_name }}">
                       </div>
                       <div class="float-start mt-4 pt-2 ms-3">
                           <h6 class="card-subtitle mb-2 text-muted">Автор: <a style="color: gray; text-decoration: none;" href="{% url 'user' question.author.id %}">{{ question.author.first_name }}</a></h6>
                           <h6 class="card-subtitle mb-2 text-muted">Дата: {{ question.date|date:"j E Y" }}</h6>
                       </div>
                    </div>
                    <div id="edit-field">
                        <h5 class="card-title">{{ question.title }}</h5>
                        <p class="card-text support-line-breaks">{{ question.text }}</p>
                    </div>

                    <button class="like-btn btn btn-sm btn-primary {% if user in question.like.all %}active{% endif %} float-end" type="submit" data-url="{% url 'ask:like' question.id %}" data-qid="{{question.id}}"><i class="far fa-thumbs-up"></i> <span class="like_count">{{ question.like.count }}</span></button>
                </div>
            </div>
        </div>
    </div>
    <div class="text-center">
        <h3>Ответы:</h3>
    </div>
    {% if question.answer_set.all %}
    {% for answer in question.answer_set.all %}
    <div class="row justify-content-center my-3">
        <div class="col-sm col-md-9">
            <div class="clearfix">
                {% if user.id == answer.author.id %}
                <a href="{% url 'ask:delete_answer' answer.id %}" class="float-end me-2" style="color:gray" onclick="return confirm('Вы уверены?');"><i class="far fa-trash-alt"></i></a>
                {% endif %}
                <div class="user-pic-answer float-start mb-3">
                    <img src="{{ answer.author.profile.image.url }}" alt="{{ answer.author.first_name }}">
                </div>
                <div class="float-start mt-1 ms-3">
                    <h6 class="mb-1 text-muted">Автор: <a style="color: gray; text-decoration: none;" href="{% url 'user' answer.author.id %}">{{ answer.author.first_name }}</a></h6>
                    <h6 class="mb-1 text-muted">Дата: {{ answer.date|date:"j E Y" }}</h6>
                </div>
            </div>
            <p class="mx-2 support-line-breaks">{{ answer.text }}</p>
            <hr>
        </div>
    </div>
    {% endfor %}
    {% else %}
    <div class="text-center">
        <p>Пока здесь нет ответов. Вы можете стать первым</p>
    </div>
    {% endif %}
    <div class="text-center">
        <h3>Предложите свой ответ:</h3>
    </div>
    {% if user.is_authenticated %}
    <div class="row justify-content-center">
        <div class="col-md-9">
            <form method="post">
                {% csrf_token %}
                {{ reply_form.text }}
                <input class="btn btn-primary my-2" type="submit" value="Ответить"">
            </form>
        </div>
    </div>
    {% else %}
    <div class="row text-center my-3">
        <p>Для добавления ответа Вам необходимо <a href="{% url 'login' %}?next={% url 'ask:question' question.id %}">войти на сайт</a> или <a href="{% url 'signup' %}">зарегистрироваться</a>.</p>
    </div>
    {% endif %}
</main>
{% endblock %}
{% load static %}
{% block script %}
<script type="module" src="{% static 'ask/question.js' %}"></script>
{% endblock %}